### ISSUE TITLE
can use for solar hijri persian calendar

### ISSUE THREAD

**Issue by movahhed** [salsowelim/odoo_hijri_datepicker#1]
Hi, my friend, can you help me make a solar calendar for Odo 12?

**Comment by salsowelim** [comment]
Hi,  
This is out of the scope of this repo unfortunately. But I will try to give a basic guideline. Hope this works for you:
- This is an odoo 11 module.You may need to do some sort of an upgrade if necessary to make this module works on odoo 12. 
- This module depends on jQuery calendar for calculation/date retrieval. If you, say, hook a solar calendar instead of ummalqura calendar, and adjust the code accordingly, it might just works.
